//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    //using Models.Interfaces;
    public partial class cadE911Log : INotifyPropertyChanged //, IPTSChangeTracking
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChangedEventHandler handler = PropertyChanged;
            if (handler != null) handler(this, new PropertyChangedEventArgs(propertyName));
        }
        private int _ptse911id;
        public int ptsE911ID { get { return _ptse911id; } set { _ptse911id = value; OnPropertyChanged(nameof(ptsE911ID)); } }
        private string _datastream;
        public string DataStream { get { return _datastream; } set { _datastream = value; OnPropertyChanged(nameof(DataStream)); } }
        private string _stationid;
        public string StationID { get { return _stationid; } set { _stationid = value; OnPropertyChanged(nameof(StationID)); } }
        private Nullable<byte> _eid;
        public Nullable<byte> EID { get { return _eid; } set { _eid = value; OnPropertyChanged(nameof(EID)); } }
        private Nullable<System.DateTime> _calldatetime;
        public Nullable<System.DateTime> CallDateTime { get { return _calldatetime; } set { _calldatetime = value; OnPropertyChanged(nameof(CallDateTime)); } }
        private string _lastname;
        public string LastName { get { return _lastname; } set { _lastname = value; OnPropertyChanged(nameof(LastName)); } }
        private string _firstname;
        public string FirstName { get { return _firstname; } set { _firstname = value; OnPropertyChanged(nameof(FirstName)); } }
        private Nullable<int> _addressnumber;
        public Nullable<int> AddressNumber { get { return _addressnumber; } set { _addressnumber = value; OnPropertyChanged(nameof(AddressNumber)); } }
        private string _addresssuffix;
        public string AddressSuffix { get { return _addresssuffix; } set { _addresssuffix = value; OnPropertyChanged(nameof(AddressSuffix)); } }
        private string _addresspredirectional;
        public string AddressPreDirectional { get { return _addresspredirectional; } set { _addresspredirectional = value; OnPropertyChanged(nameof(AddressPreDirectional)); } }
        private string _addressstreet;
        public string AddressStreet { get { return _addressstreet; } set { _addressstreet = value; OnPropertyChanged(nameof(AddressStreet)); } }
        private string _addresspostdirectional;
        public string AddressPostDirectional { get { return _addresspostdirectional; } set { _addresspostdirectional = value; OnPropertyChanged(nameof(AddressPostDirectional)); } }
        private string _addressunitnumber;
        public string AddressUnitNumber { get { return _addressunitnumber; } set { _addressunitnumber = value; OnPropertyChanged(nameof(AddressUnitNumber)); } }
        private string _community;
        public string Community { get { return _community; } set { _community = value; OnPropertyChanged(nameof(Community)); } }
        private string _state;
        public string State { get { return _state; } set { _state = value; OnPropertyChanged(nameof(State)); } }
        private string _areacode;
        public string AreaCode { get { return _areacode; } set { _areacode = value; OnPropertyChanged(nameof(AreaCode)); } }
        private string _telephone;
        public string Telephone { get { return _telephone; } set { _telephone = value; OnPropertyChanged(nameof(Telephone)); } }
        private string _esn;
        public string ESN { get { return _esn; } set { _esn = value; OnPropertyChanged(nameof(ESN)); } }
        private string _policeagency;
        public string PoliceAgency { get { return _policeagency; } set { _policeagency = value; OnPropertyChanged(nameof(PoliceAgency)); } }
        private string _fireagency;
        public string FireAgency { get { return _fireagency; } set { _fireagency = value; OnPropertyChanged(nameof(FireAgency)); } }
        private string _xcoordinate;
        public string XCoordinate { get { return _xcoordinate; } set { _xcoordinate = value; OnPropertyChanged(nameof(XCoordinate)); } }
        private string _ycoordinate;
        public string YCoordinate { get { return _ycoordinate; } set { _ycoordinate = value; OnPropertyChanged(nameof(YCoordinate)); } }
        private string _notes;
        public string Notes { get { return _notes; } set { _notes = value; OnPropertyChanged(nameof(Notes)); } }
        private string _extraphone1;
        public string ExtraPhone1 { get { return _extraphone1; } set { _extraphone1 = value; OnPropertyChanged(nameof(ExtraPhone1)); } }
        private string _extraphone2;
        public string ExtraPhone2 { get { return _extraphone2; } set { _extraphone2 = value; OnPropertyChanged(nameof(ExtraPhone2)); } }
        private string _flags;
        public string Flags { get { return _flags; } set { _flags = value; OnPropertyChanged(nameof(Flags)); } }
        private bool _isdeleted;
        public bool IsDeleted { get { return _isdeleted; } set { _isdeleted = value; OnPropertyChanged(nameof(IsDeleted)); } }
        private Nullable<System.DateTime> _deleted;
        public Nullable<System.DateTime> Deleted { get { return _deleted; } set { _deleted = value; OnPropertyChanged(nameof(Deleted)); } }
        private string _deletedby;
        public string DeletedBy { get { return _deletedby; } set { _deletedby = value; OnPropertyChanged(nameof(DeletedBy)); } }
        private string _deletedip;
        public string DeletedIP { get { return _deletedip; } set { _deletedip = value; OnPropertyChanged(nameof(DeletedIP)); } }
        private Nullable<System.DateTime> _created;
        public Nullable<System.DateTime> Created { get { return _created; } set { _created = value; OnPropertyChanged(nameof(Created)); } }
        private string _createdby;
        public string CreatedBy { get { return _createdby; } set { _createdby = value; OnPropertyChanged(nameof(CreatedBy)); } }
        private Nullable<System.DateTime> _updated;
        public Nullable<System.DateTime> Updated { get { return _updated; } set { _updated = value; OnPropertyChanged(nameof(Updated)); } }
        private string _updatedby;
        public string UpdatedBy { get { return _updatedby; } set { _updatedby = value; OnPropertyChanged(nameof(UpdatedBy)); } }
        private string _updatedip;
        public string UpdatedIP { get { return _updatedip; } set { _updatedip = value; OnPropertyChanged(nameof(UpdatedIP)); } }
        private Nullable<System.Guid> _rowguid;
        public Nullable<System.Guid> ROWGUID { get { return _rowguid; } set { _rowguid = value; OnPropertyChanged(nameof(ROWGUID)); } }
        private bool _isparsesuccessful;
        public bool IsParseSuccessful { get { return _isparsesuccessful; } set { _isparsesuccessful = value; OnPropertyChanged(nameof(IsParseSuccessful)); } }
    }
}
